#!/usr/bin/env python3
"""
Build Nanobot wheel and install it into desktop/runtime/site-packages/.
"""

import argparse
import hashlib
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path


def file_sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while chunk := f.read(65536):
            h.update(chunk)
    return h.hexdigest()


def find_standalone_python(desktop_dir: Path) -> Path:
    dest_dir = desktop_dir / "runtime" / "python"
    exe_name = "python.exe" if platform.system().lower() == "windows" else "bin/python3"
    exe_path = dest_dir / exe_name
    if not exe_path.is_file():
        raise FileNotFoundError(
            f"Standalone Python executable not found at {exe_path}. "
            "Please run fetch_python_runtime.py first."
        )
    return exe_path


def build_wheel(repo_root: Path, out_dir: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    # Clean old wheels in out_dir
    for old_whl in out_dir.glob("*.whl"):
        try:
            old_whl.unlink()
        except OSError:
            pass

    print(f"Building nanobot wheel via `uv build --wheel` into {out_dir} ...")
    cmd = ["uv", "build", "--wheel", "--out-dir", str(out_dir)]
    res = subprocess.run(cmd, cwd=str(repo_root), check=True)
    if res.returncode != 0:
        raise RuntimeError("`uv build --wheel` failed.")

    wheels = list(out_dir.glob("*.whl"))
    if not wheels:
        raise FileNotFoundError(f"No .whl file found in {out_dir}")
    # Sort by modification time, newest first
    wheels.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    print(f"Built wheel: {wheels[0].name}")
    return wheels[0]


def install_into_target(
    python_exe: Path,
    wheel_path: Path,
    target_dir: Path,
    extras: str | None = None,
    force: bool = False,
) -> bool:
    target_dir.mkdir(parents=True, exist_ok=True)
    hash_file = target_dir / ".wheel_sha256"
    wheel_hash = file_sha256(wheel_path)

    if not force and hash_file.is_file():
        try:
            cached_hash = hash_file.read_text(encoding="utf-8").strip()
            if cached_hash == wheel_hash:
                print(f"Wheel hash {wheel_hash[:12]} matches cached installation. Skipping pip install.")
                return False
        except Exception:
            pass

    spec = str(wheel_path)
    if extras:
        spec = f"{wheel_path}[{extras}]"

    print(f"Installing {spec} into {target_dir} ...")
    cmd = [
        str(python_exe),
        "-m",
        "pip",
        "install",
        "--target",
        str(target_dir),
        "--upgrade",
        "--no-compile",
        spec,
    ]

    subprocess.run(cmd, check=True)

    # Ensure sitecustomize.py exists in target_dir so that .pth files (e.g. pywin32.pth)
    # are processed when target_dir is added to PYTHONPATH
    sitecustomize_path = target_dir / "sitecustomize.py"
    sitecustomize_code = (
        "# Automatically generated by build_python_runtime.py\n"
        "import os\n"
        "import site\n\n"
        "_dir = os.path.dirname(os.path.abspath(__file__))\n"
        "site.addsitedir(_dir)\n"
    )
    sitecustomize_path.write_text(sitecustomize_code, encoding="utf-8")

    # Also register target_dir in standalone Python's internal site-packages
    try:
        cmd = [str(python_exe), "-c", "import site; print(site.getsitepackages()[-1])"]
        res = subprocess.run(cmd, capture_output=True, text=True, check=True)
        py_site_pkg = Path(res.stdout.strip())
        if py_site_pkg.is_dir():
            pth_file = py_site_pkg / "_desktop_runtime.pth"
            pth_file.write_text(
                f"import os, site; site.addsitedir(r'{target_dir}')\n",
                encoding="utf-8",
            )
    except Exception as exc:
        print(f"Notice: could not configure internal .pth: {exc}")

    hash_file.write_text(wheel_hash, encoding="utf-8")
    print(f"Successfully installed into {target_dir}")
    return True


def verify_installation(python_exe: Path, target_dir: Path):
    print("Verifying installed package data...")
    nanobot_pkg = target_dir / "nanobot"
    if not nanobot_pkg.is_dir():
        raise FileNotFoundError(f"nanobot package not found at {nanobot_pkg}")

    dist_index = nanobot_pkg / "web" / "dist" / "index.html"
    if not dist_index.is_file():
        raise FileNotFoundError(f"Missing required WebUI bundle at {dist_index}")
    print(f"  [OK] {dist_index.relative_to(target_dir)} exists")

    skills_dir = nanobot_pkg / "skills"
    if not skills_dir.is_dir():
        raise FileNotFoundError(f"Missing skills directory at {skills_dir}")
    print(f"  [OK] {skills_dir.relative_to(target_dir)} exists")

    templates_dir = nanobot_pkg / "templates"
    if not templates_dir.is_dir():
        raise FileNotFoundError(f"Missing templates directory at {templates_dir}")
    print(f"  [OK] {templates_dir.relative_to(target_dir)} exists")

    # Test importing nanobot with standalone python
    print("Testing import via standalone Python interpreter...")
    env = os.environ.copy()
    env["PYTHONPATH"] = str(target_dir)

    cmd = [
        str(python_exe),
        "-c",
        "import nanobot; print(f'Successfully imported nanobot v{nanobot.__version__}')",
    ]
    res = subprocess.run(cmd, env=env, capture_output=True, text=True, check=True)
    print(f"  [OK] {res.stdout.strip()}")


def main():
    parser = argparse.ArgumentParser(description="Build and install Nanobot runtime dependencies")
    parser.add_argument("--extras", type=str, default="api", help="Optional package extras to install (default: 'api')")
    parser.add_argument("--force", action="store_true", help="Force reinstall even if wheel hash matches")
    args = parser.parse_args()

    desktop_dir = Path(__file__).resolve().parent.parent
    repo_root = desktop_dir.parent
    cache_dist_dir = desktop_dir / ".cache" / "dist"
    target_site_packages = desktop_dir / "runtime" / "site-packages"

    python_exe = find_standalone_python(desktop_dir)
    wheel_path = build_wheel(repo_root, cache_dist_dir)
    install_into_target(python_exe, wheel_path, target_site_packages, extras=args.extras, force=args.force)
    verify_installation(python_exe, target_site_packages)


if __name__ == "__main__":
    main()
